📦
973 /agent/index.js.map
549 /agent/index.js
1558 /agent/scanner.js.map
752 /agent/scanner.js
✄
{"version":3,"file":"index.js","names":["scanner","rpc","exports","scanRange","async","pattern","range","rawPattern","r","base","NativePointer","size","protection","searchPattern","enumerateMemoryRanges","specifier","Process","enumerateRanges","hexDump","addr","address","hex_dump","readByteArray","setExceptionHandler","_","main","then","catch","err"],"sourceRoot":"/Users/caduplooy/Data/projects/frida-scan/agent/agent/","sources":["index.ts"],"mappings":"kBAASA,MAAe,eAExBC,IAAIC,QAAU,CACVC,UAAWC,eAAgBC,EAAcC,EAAYC,GAAsB,GAEvE,MAAMC,EAAI,CACNC,KAAM,IAAIC,cAAcJ,EAAMG,MAC9BE,KAAML,EAAMK,KACZC,WAAYN,EAAMM,YAGtB,OAAIL,QACaP,EAAQG,UAAUE,EAASG,SAE3BR,EAAQG,UAAUH,EAAQa,cAAcR,GAAUG,EAEvE,EAKAM,sBAAuB,SAAUC,EAAoB,OACjD,OAAOC,QAAQC,gBAAgBF,EACnC,EAEAG,QAAS,SAAUC,EAAWR,GAC1B,MAAMS,EAAU,IAAIV,cAAcS,GAClC,OAAOnB,EAAQqB,SAASD,EAAST,EACrC,EAEAW,cAAe,SAASH,EAAWR,GAE/B,OADgB,IAAID,cAAcS,GACnBG,cAAcX,EACjC,GAMJP,iBACIY,QAAQO,qBAAoBC,IACjB,GAEf,CAEAC,GAAOC,MAAK,SAETC,OAAOC,IAAD"}
✄
import{scanner as e}from"./scanner.js";rpc.exports={scanRange:async function(n,t,r=!1){const a={base:new NativePointer(t.base),size:t.size,protection:t.protection};return r?await e.scanRange(n,a):await e.scanRange(e.searchPattern(n),a)},enumerateMemoryRanges:function(e="r--"){return Process.enumerateRanges(e)},hexDump:function(n,t){const r=new NativePointer(n);return e.hex_dump(r,t)},readByteArray:function(e,n){return new NativePointer(e).readByteArray(n)}},async function(){Process.setExceptionHandler((e=>!0))}().then((()=>{})).catch((e=>{}));
✄
{"version":3,"file":"scanner.js","names":["scanner","strToHex","buffer","arr","i","length","charCodeAt","toString","slice","join","flipHexStringEndianess","hex","result","j","substring","hex_dump","addr","size","hexdump","offset","header","ansi","searchPattern","query","scanRange","pattern","range","matches","Promise","accept","Memory","scan","base","onMatch","address","push","spaceLeft","add","sub","toUInt32","onError","reason","onComplete"],"sourceRoot":"/Users/caduplooy/Data/projects/frida-scan/agent/agent/","sources":["scanner.ts"],"mappings":"OAAM,IAAWA,SAAjB,SAAiBA,GACb,SAAgBC,EAASC,GAErB,IADA,IAAIC,EAAM,GACDC,EAAI,EAAGA,EAAIF,EAAOG,OAAQD,IAC/BD,EAAIC,GAAMF,EAAOI,WAAWF,GAAGG,SAAS,IAAKC,OAAO,GAExD,OAAOL,EAAIM,KAAK,GACpB,CAYA,SAAgBC,EAAuBC,GACnC,IAAIC,EAAS,GACb,IAAK,IAAIR,EAAI,EAAGS,EAAIF,EAAIN,OAAQD,EAAIO,EAAIN,OAAS,EAAGD,IAAKS,GAAK,EAE1DD,GAAkBD,EAAIG,UAAUD,EAAI,EAAGA,GAE3C,OAAOD,CACX,CAzBgBZ,EAAAC,SAAQA,EAQRD,EAAAe,SAAhB,SAAyBC,EAAqBC,GAC1C,OAAOC,QAAQF,EAAM,CACjBG,OAAQ,EACRd,OAAQY,EACRG,QAAQ,EACRC,MAAM,GAEd,EAGgBrB,EAAAU,uBAAsBA,EAUtBV,EAAAsB,cAAhB,SAA8BC,GAC1B,GAAoB,iBAATA,EAAmB,CAC1B,IAAIX,EAASW,EAAMhB,SAAS,IAK5B,OAJIK,EAAOP,OAAS,IAChBO,EAAS,IAAMA,GAGZF,EAAuBE,E,CAGlC,OAAOX,EAASsB,EACpB,EAQgBvB,EAAAwB,UAAhB,SAA0BC,EAAiBC,GACvC,IAAIC,EAAmB,GACvB,OAAO,IAAIC,SAASC,IAChBC,OAAOC,KAAKL,EAAMM,KAAMN,EAAMT,KAAMQ,EAAS,CACzCQ,QAAS,SAAUC,EAASjB,GACxBU,EAAQQ,KAAK,CACTD,UACAjB,OACAmB,UAAWV,EAAMM,KAAKK,IAAIX,EAAMT,MAAMqB,IAAIJ,EAAQG,IAAIpB,IAAOsB,YAErE,EACAC,QAAS,SAAUC,GAEnB,EACAC,WAAY,WACRb,EAAOF,EACX,GACF,GAGV,CACH,CArED,CAAiB3B,kBAAO"}
✄
export var scanner;!function(n){function e(n){for(var e=[],t=0;t<n.length;t++)e[t]=n.charCodeAt(t).toString(16).slice(-4);return e.join("")}function t(n){let e="";for(let t=0,r=n.length;t<n.length/2;t++,r-=2)e+=n.substring(r-2,r);return e}n.strToHex=e,n.hex_dump=function(n,e){return hexdump(n,{offset:0,length:e,header:!0,ansi:!0})},n.flipHexStringEndianess=t,n.searchPattern=function(n){if("number"==typeof n){let e=n.toString(16);return e.length%2&&(e="0"+e),t(e)}return e(n)},n.scanRange=function(n,e){let t=[];return new Promise((r=>{Memory.scan(e.base,e.size,n,{onMatch:function(n,r){t.push({address:n,size:r,spaceLeft:e.base.add(e.size).sub(n.add(r)).toUInt32()})},onError:function(n){},onComplete:function(){r(t)}})}))}}(scanner||(scanner={}));